name: pull-request-ci

on:
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Run unit tests
      run: npm test

    # Uncomment and configure the following steps to use SonarQube for SAST
    # - name: Set up SonarQube Scanner
    #   uses: sonarsource/sonarcloud-github-action@v1.9.0

    # - name: Run SonarQube Scanner
    #   env:
    #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    #   run: |
    #     sonar-scanner \
    #       -Dsonar.projectKey=your_project_key \
    #       -Dsonar.organization=your_organization_key \
    #       -Dsonar.sources=. \
    #       -Dsonar.host.url=https://sonarcloud.io \
    #       -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info
